name: myenv
channels:
  - conda-forge
dependencies:
  - pangeo-notebook==2020.07.03
  - xarray
  - hvplot
  - pip
  - pip:
    - sat-search
    - git+https://github.com/stv0g/nbgitpuller.git@f735265f7b2a429a17a8fab70cfd3557f060640d
